version: "3.9"

services:
  backend:
    build:
      context: ./back-biblioteca
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build:
      context: ./front-biblioteca
      dockerfile: Dockerfile
    container_name: front_c
    ports:
      - "5173:5173"
    depends_on:
      - backend
  mysql:
    build:
      context: .
      dockerfile: DockerfileMysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: library-grema
      MYSQL_USER: biblioteca
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
