version: "3.9"

services:
  backend:
    build:
      context: ./back-biblioteca
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front-biblioteca
      dockerfile: Dockerfile
    container_name: front_c
    ports:
      - "5173:5173"
    depends_on:
      - backend

