
USE library-grema;


        
INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000002A', 'zeus', '00', 'zeus@olimpo.com', '2000-10-14', 625677893, 'Olimpeion', 'www.foroDioses.com', 'superusuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000003A', 'hercules', '00', 'hercules@olimpo.com', '2010-01-18', 626579754, 'Olimpeion', 'www.academia.com', 'usuario');


INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000004A', 'poseidon', '00', 'poseidon@mar.com', '2000-02-12', 600044001, 'Olimpeion', 'www.maratlantico.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000005A', 'hades', '00', 'hades@olimpo.com', '2005-12-14', 600220001, 'Olimpeion', 'www.mi-primera-pagina.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000006A', 'hera', '00', 'hera@olimpo.com', '2011-10-03', 623245678, 'Olimpeion', 'www.superhera.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000007A', 'atenea', '00', 'atenea@olimpo.com', '2000-11-14', 600375601, 'Olimpeion', 'www.atenas.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000008A', 'afrodita', '00', 'afrodita@olimpo.com', '1995-03-10', 623234561, 'Olimpeion', 'www.superafrodita.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000009A', 'apolo', '00', 'apolo@olimpo.com', '1998-09-28', 678687432, 'Olimpeion', 'www.apolocatorce.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000010A', 'hermes', '00', 'hermes@olimpo.com', '1980-04-26', 673245245, 'Olimpeion', 'www.hermeticos.com', 'usuario');

INSERT INTO usuario (nif, nombre, password, correoElectronico, fechaNacimiento, telefono, direccion, webPersonal, rol) 
VALUES('00000011A', 'ares', '00', 'ares@olimpo.com', '1976-12-01', 688234234, 'Olimpeion', 'www.aresares.com', 'usuario');


INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('La vida es bella', 'Jose Juan', '34', 10, 'Nenuco', '2000-12-01', 'Ingles', 'Frances', 100, 'La vida es bella es una pelicula italiana dirigida por Roberto Benigni y estrenada en 1997. La historia se desarrolla en la Italia fascista durante la Segunda Guerra Mundial y cuenta la historia de Guido, un hombre judio que se enamora de una mujer no judia llamada Dora. Juntos tienen un hijo llamado Giosue y la familia es deportada a un campo de concentracion nazi.', 3, 'libro', 'Drama', 2, 'https://www.giglon.com/documents/10180/30003/3-20811x1-7f5pv.jpg/a37bd66d-7d43-4aae-a9d4-d1ce3dbe071c', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Memorias del comunismo', 'Federico Jimenez Losantos', '9788491641780', 16, 'Planeta de los libros', '2003-09-14', 'Espannol', 'Espannol', 277, 'Buceando en las fuentes originales -de Marx, Bakunin y Lenin al Che o Pablo Iglesias-, este libro explica la naturaleza real del comunismo, sus raices filosoficas y politicas, los errores habituales sobre su historia y el hecho mas terrible: que, cien annos y cien millones de muertos despues, siga siendo una ideologia respetada entre politicos, profesores y periodistas. En dos paises europeos, Rusia y Espanna, se intento crear en el siglo XX un regimen comunista. En Rusia, tras cinco annos de feroz guerra civil de Lenin contra su pueblo, el comunismo triunfo. En Espanna, tras una atroz guerra civil de tres annos, perdio. Pero se discute el papel de Stalin en la guerra -de Paracuellos y la muerte de Nin al oro del Banco de Espanna- y se oculta la actuacion de los dos comunismos espannoles: el marxista del PCE, el PSOE bolchevizado o el POUM; y el bakuninista de la CNT-FAI, que impuso el terror rojo en Catalunna con la ayuda entusiasta de Companys. Ni la Rusia bajo la Cheka ni la Espanna bajo las checas se recuerdan hoy. Solo eso y el exito de la propaganda sovietica desde 1917 explican la irrupcion y el exito de Podemos.', 36, 'libro', 'Politica', 2, null, null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('HISTORIA SECRETA DE MIS MEJORES CANCIONES', 'MIGUEL BOSE', '9788467066562', 12, 'HarperCollins', '2003-09-14', 'Espannol', 'Espannol', 123, 'Me temo que este libro va a romper muchas ilusiones. Tambien historias arraigadas desde hace tiempo. Lo siento. No es mi intencion ni la de este recopilatorio. Pero creo que, tras tantos annos de licencia, llego el momento de descifrar los secretos escondidos, esos que he venido guardando en cada una de estas 68 canciones. Entrad en el maravilloso mundo de mis laberintos, y desvelad lo que nadie sabe. Pero solo si sois valientes. A medida que Miguel Bose nos desvela la intencion de sus letras, iras encontrando fotografias a todo color ineditas del autor, las portadas de sus discos y codigos QR para escuchar las canciones. Sin duda, su obra mas personal.', 1, 'libro', 'Biografia', 3, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1677689798/library/jfkron6n1dxs1nuhfh6x.jpg', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', '978-8478886456', 13, 'Simon & Schuster', '2009-05-12', 'Frances', 'Espannol', 223, 'Harry Potter y la Piedra Filosofal es el primer libro de la famosa saga escrita por J.K. Rowling. La historia sigue a Harry Potter, un ninno huerfano que descubre que es un mago y es aceptado en la escuela de magia y hechiceria de Hogwarts. Alli, Harry se enfrenta a misterios, amistades y desafios mientras descubre su lugar en el mundo magico. Junto a sus amigos Ron y Hermione, Harry debe encontrar la Piedra Filosofal, un objeto legendario con poderes inimaginables, antes de que caiga en manos equivocadas. Esta emocionante aventura lo lleva a descubrir su verdadero destino y enfrentarse al malvado Lord Voldemort.', 2, 'libro', 'Fantasia', 4, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686139638/library/lv4ocnf4f0jmygcwn2vt.jpg', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Como nos arreglamos', 'ERNESTO CANALES SANTOS', '9786073172448', 7, 'Hachette Livre', '2000-12-02', 'Espannol', 'Ingles', 123, 'Ernesto Canales narra aqui como paso, a sus 75 annos, de ser un exitoso abogado a convertirse en el primer fiscal mexicano especializado en perseguir los delitos de corrupcion, asi como los retos que enfrento durante los dos annos que cumplio ese papel y los logros historicos que su trabajo lego en la administracion publica del pais. Al mismo tiempo, denuncia a los principales operadores criminales del sistema, desde las cupulas politicas, y ofrece la relacion detallada de sus procedimientos, develando los obstaculos que se han creado para sostener el sistema de impunidad y corrupcion hasta la fecha. Porque su gestion no conto con el apoyo de la sociedad civil y, por encima de todo, no estuvo exenta de intimidaciones, trabas y la poca participacion de los funcionarios, factores que impidieron constantemente su labor.', 3, null, 'Biografia', 0, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686139969/library/u07du9bgfpenj3kuymdh.jpg', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Filosofia felina ', 'John Gray', '9788418342530', 7, 'Scholastic Corporation', '2003-09-14', 'Ingles', 'Espannol', 168, 'Todos envidiamos el aristocratico desapego con el que los gatos contemplan el mundo y lo comodos que parecen sentirse en su propio pellejo, como si supieran algo fundamental que nosotros ignoramos.	John Gray, uno de los grandes pensadores de nuestra epoca, defiende que tenemos mucho que aprender de los gatos y de su comportamiento, y partiendo de su experiencia personal con estos misteriosos y carismaticos animales, y acudiendo tambien a las brillantes paginas que les han dedicado autores como Montaigne, Junichiro Tanizaki o Patricia Highsmith, nos propone una suerte de filosofia felina que sirva de guia para una vida mas autentica y sosegada.	Las preguntas sobre el sentido de la existencia y el secreto de la felicidad nos persiguen desde los albores de la civilizacion, y quiza en esas lides, sugiere Gray, los gatos sean tan buenos maestros como los grandes filosofos.', 5, null, 'Ficcion', 2, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686140559/library/jt7urvryxwtdedntijs0.jpg', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Cada historia cuenta', 'Varios autores', '9786073172448', 7, 'Pearson Education', '2003-09-14', 'Espannol', 'Ingles', 123, 'Cada historia cuenta es un libro solidario de relatos que recoge las historias presentadas a la I edicion del Concurso de Relatos Cada historia cuenta lanzado por la Fundacion AINDACE. El lector o lectora encontrara entre sus paginas historias reales, vivencias y reflexiones personales sobre la discapacidad, desde una mirada positiva y enriquecedora, con historias  transcendentes de superacion, capaces de empoderar, inspirar y motivar a otras personas. Se trata de un libro solidario donde parte de los beneficios obtenidos por su venta iran destinados a la Fundacion AINDACE, cuya mision fundamental es ayudar a personas con danno cerebral a traves de la financiacion de proyectos de investigacion.', 4, null, 'Historias', 0, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686140332/library/jrtf6c64iqyydl75d26c.jpg', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Heredera de fuego', ' SARAH J. MAAS', '9788418359309', 0, 'Oxford University Press', '2003-09-14', 'Ingles', 'Espannol', 672, 'Como asesina del rey, Celaena Sardothien esta obligada a servir al tirano que asesino a su mejor amiga. Pero se ha prometido a si misma que se lo hara pagar. Las respuestas que Celaena necesita para destruir al rey se encuentran mas alla del mar, en Wendlyn. Y Chaol, capitan de la guardia real, ha puesto su futuro en peligro al enviarla alli. Y mientras Celaena busca su destino en Wendlyn, una nueva amenaza se prepara para asaltar los cielos. Encontrara Celaena las fuerzas necesarias no solo para ganar sus propias batallas, sino para ir a una guerra que podria poner a prueba la lealtad hacia los suyos y enfrentarla a aquellos que han llegado a convertirse en sus seres mas queridos?', 23, null, 'Ficcion', 2, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686140666/library/cmbbi9c7x3dfxt8ifjqh.webp', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('El viento conoce mi nombre', 'ISABEL ALLENDE', '9788401032004', 16, 'Oxford University Press', '2002-02-17', 'Espannol', 'Frances', 352, 'Viena, 1938. Samuel Adler es un ninno judio de seis annos cuyo padre desaparece durante la Noche de los Cristales Rotos, en la que su familia lo pierde todo. Su madre, desesperada, le consigue una plaza en un tren que le llevara desde la Austria nazi hasta Inglaterra. Samuel emprende una nueva etapa con su fiel violin y con el peso de la soledad y la incertidumbre, que lo acompannaran siempre en su dilatada vida.', 7, null, 'Suspense', 2, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686140859/library/tfijzfiteh1fayopjon6.jpg', null, null);
INSERT INTO libro (titulo, autores, isbn, edad, editorial, fechaEdicion, lenguaPublicacion, lenguaTraduccion, numeroPaginas, descripcion, edicion, formato, genero, copias, portada, imagen2, imagen3) VALUES ('Las brujas de Brooklyn', 'SOPHIE ESCABASSE', '9788468353708', 3, 'Cambridge University Press', '2008-11-14', 'Ingles', 'Espannol', 240, 'Hay una nueva bruja en la ciudad  Effie tiene nuevo hogar, nueva escuela y nuevos amigos (aunque resulte dificil al principio); pero su nueva vida en Brooklyn se vuelve aun mas extranna cuando Effie descubre que la MAGIA le viene de familia...  Las brujas de Brooklyn es el primer libro de la trilogia. El comic lo ha escrito y dibujado Sophie Escabasse, ilustradora francesa que vive en Nueva York. Esta es su primera novela grafica aunque ha publicado otros libros como ilustradora', 1, null, 'Literatura infantil', 2, 'https://res.cloudinary.com/dnsxhjncj/image/upload/v1686140976/library/kpev4ixzs0vyllglyqpb.jpg', null, null);
